#!/usr/bin/env python3
"""
run_demo.py

Convenience script that runs the full SOC Storyteller pipeline against
the bundled synthetic scenario in ``sample_logs/attack_scenario.xml``
(generated by ``sample_logs/generate_sample_data.py``), and writes
Markdown, HTML, JSON, and PDF reports to ``output/demo_report.*``.

This exists purely so a new user (or CI) can see the whole project work
end-to-end in one command, with zero setup and no real .evtx file
required:

    python run_demo.py

To analyze a real .evtx file instead, use ``main.py --input <file>``.
"""

from __future__ import annotations

from pathlib import Path

from correlation.correlation_engine import CorrelationEngine
from detections.base import DetectionEngine
from detections.rules import default_rule_set
from parser.evtx_parser import EvtxParser
from reports.narrative_generator import NarrativeGenerator
from reports.report_generator import ReportGenerator
from risk_engine.risk_calculator import RiskCalculator
from utils.logger import configure_logging, get_logger

logger = get_logger(__name__)

_SAMPLE_XML = Path(__file__).parent / "sample_logs" / "attack_scenario.xml"
_OUTPUT_DIR = Path(__file__).parent / "output"


def main() -> None:
    """Run the demo pipeline end-to-end and print a summary."""
    configure_logging(verbose=False)

    if not _SAMPLE_XML.exists():
        logger.info("Sample scenario not found, generating it now...")
        from sample_logs.generate_sample_data import main as generate_sample

        generate_sample()

    parser = EvtxParser()
    events = parser.parse_xml_events_file(_SAMPLE_XML)
    print(f"Loaded {len(events)} events from synthetic sample scenario.")

    detection_engine = DetectionEngine().register_all(default_rule_set())
    detections = detection_engine.run(events)
    print(f"Detections found: {len(detections)}")

    chains = CorrelationEngine(max_gap_minutes=60).correlate(detections)
    risk_calculator = RiskCalculator()
    scored_chains = risk_calculator.score_chains(chains)
    overall_score = risk_calculator.overall_incident_score(scored_chains)

    NarrativeGenerator().generate_all(scored_chains)

    print(f"\nAttack chains identified: {len(scored_chains)}")
    print(f"Overall incident risk score: {overall_score}/100\n")

    for chain in scored_chains:
        severity = chain.risk_severity.value if chain.risk_severity else "UNSCORED"
        print(f"--- {chain.chain_id} | {chain.host} | {severity} ({chain.risk_score}/100) ---")
        print(chain.narrative)
        print()

    report_generator = ReportGenerator()
    md = report_generator.render_markdown(
        scored_chains, title="SOC Storyteller Demo Report", overall_score=overall_score
    )
    html = report_generator.render_html(
        scored_chains, title="SOC Storyteller Demo Report", overall_score=overall_score
    )
    json_report = report_generator.render_json(scored_chains, overall_score=overall_score)
    pdf_report = report_generator.render_pdf(
        scored_chains, title="SOC Storyteller Demo Report", overall_score=overall_score
    )

    report_generator.save(md, _OUTPUT_DIR / "demo_report.md")
    report_generator.save(html, _OUTPUT_DIR / "demo_report.html")
    report_generator.save(json_report, _OUTPUT_DIR / "demo_report.json")
    report_generator.save(pdf_report, _OUTPUT_DIR / "demo_report.pdf")

    print(f"Reports written to: {_OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    main()
